name: Build and test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - develop
      - feature_*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    container:
      image: ghcr.io/aosedge/aos-core-build-base:latest
      options: "--entrypoint /usr/bin/bash"
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      # Apply solution to "HOME is overridden for containers" problem: https://github.com/actions/runner/issues/863
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ../
          cmake ../ -DWITH_TEST=ON -DWITH_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug
          make; make tests; make coverage

      - name: Upload codecov report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.total
