name: Build (Debug) and test

on:
  push:
    branches:
      - main
      - develop
      - feature*
      - release*

  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

    branches:
      - main
      - develop
      - feature*
      - release*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    container:
      image: ghcr.io/aosedge/aos-core-build:latest
      options: "--entrypoint /usr/bin/bash"
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install build wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v7

      - name: Build (Debug)
        run: |
          ./build.sh build --ci --clean

      - name: Test
        run: |
          ./build.sh coverage

      - name: Upload codecov report
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.total

      - name: SonarQube analysis (on push)
        if: github.event_name == 'push'
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define "sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
            --define "sonar.coverageReportPaths=build/coverage_sonarqube.xml"

      - name: Save PR metadata
        if: github.event_name == 'pull_request'
        run: |
          mkdir -p ./sonar-pr-info
          echo "${{ github.event.pull_request.number }}" > ./sonar-pr-info/pr_number
          echo "${{ github.event.pull_request.head.sha }}" > ./sonar-pr-info/pr_head_sha
          echo "${{ github.event.pull_request.head.ref }}" > ./sonar-pr-info/pr_head_ref
          echo "${{ github.event.pull_request.base.ref }}" > ./sonar-pr-info/pr_base_ref

      - name: Upload SonarQube artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: sonar-data
          path: |
            build_wrapper_output_directory/
            build/coverage_sonarqube.xml
            sonar-pr-info/
            sonar-project.properties
            src/
          retention-days: 1
